import fs from 'node:fs';
import path from 'node:path';

const PUBLIC_DIR = path.resolve(process.cwd(), 'public');
const OUT_FILE = path.resolve(process.cwd(), 'server', 'embeddedAssets.ts');

function escapeString(str: string): string {
  return JSON.stringify(str);
}

const files = [
  { name: '/index.html', file: 'index.html', type: 'text/html; charset=utf-8' },
  { name: '/style.css', file: 'style.css', type: 'text/css; charset=utf-8' },
  { name: '/app.js', file: 'app.js', type: 'application/javascript; charset=utf-8' },
  { name: '/favicon.svg', file: 'favicon.svg', type: 'image/svg+xml' },
  { name: '/manifest.json', file: 'manifest.json', type: 'application/json; charset=utf-8' },
];

let tsCode = `// AUTO-GENERATED EMBEDDED ASSETS (Do not edit directly)
// Generated by scripts/bundle-assets.ts for True Single-File Standalone Binaries.

export interface EmbeddedAsset {
  content: string;
  contentType: string;
}

export const EMBEDDED_ASSETS: Record<string, EmbeddedAsset> = {
`;

for (const item of files) {
  const filePath = path.join(PUBLIC_DIR, item.file);
  if (fs.existsSync(filePath)) {
    const content = fs.readFileSync(filePath, 'utf-8');
    tsCode += `  ${JSON.stringify(item.name)}: {
    content: ${escapeString(content)},
    contentType: ${JSON.stringify(item.type)},
  },
`;
    if (item.name === '/index.html') {
      tsCode += `  '/': {
    content: ${escapeString(content)},
    contentType: ${JSON.stringify(item.type)},
  },
`;
    }
  }
}

tsCode += `};

export function getEmbeddedAsset(pathname: string): EmbeddedAsset | null {
  const normalized = pathname === '' || pathname === '/' ? '/index.html' : pathname;
  return EMBEDDED_ASSETS[normalized] || null;
}
`;

fs.writeFileSync(OUT_FILE, tsCode, 'utf-8');
console.log(`✓ Generated ${OUT_FILE} with all embedded static assets.`);
